### ISSUE TITLE
Provide advice on storing documents and agenda/minutes in SharePoint

### ISSUE THREAD

**Issue by jatonline** [Jean-Golding-Institute/ask-jgi-handbook#17]
- Review what is in the handbook at the moment
- Change indico to Sharepoint
- Where to store documents/code
    - Sharepoint folder
        - Where to create them
        - When is one needed – when documents are received/created that would be useful in future
        - Screenshot of how to sync a folder
    - GitHub – if appropriate for the project (add a link on the sharepoint)
    - Meeting agenda/minutes folder

**Comment by NatalieZelenka** [comment]
Fixed by #29
