### ISSUE TITLE
Minor improvements to the handbook

### ISSUE THREAD

**Issue by jatonline** [Jean-Golding-Institute/ask-jgi-handbook#21]
Follow on from #18, these are some additional suggestions for (minor) changes to the handbook.

- [ ] Add some details about the tracker (filling it in etc…)
- [ ] Add new links to the new sharepoint folders
- [ ] Edit the shift organization page so it is accurate for having one shifter on at a time

...with the links to SharePoint, Tracker, Slack, etc. I wonder if it's worth linking to a (newly-created) single page that links to everything external?

- this could be a useful bookmark for people
- and would mean only one place to edit when links change

**Comment by NatalieZelenka** [comment]
Fixed by @lippirk in #27
